"""Build and verify the frozen T40 post-training-quantization calibration corpus.

The corpus is deliberately derived from material this repository already
commits. Tier 1 (``t10_derived``) turns the CC0-1.0 T10 token fixtures into
prefill inputs that satisfy the frozen T12 static-cache contract, so the whole
corpus can be regenerated byte-for-byte on any machine with nothing installed
beyond the standard library and PyYAML. Tier 2 (``external_diversity``) only
*declares* revision-pinned public corpora as candidates for T41; no third-party
dataset row is ever committed here.

Nothing in this module quantizes anything. AIMET is Linux + CUDA only. What is
frozen here is the *input* half of a quantization experiment: which sequences
the range observers see, in which order, at which shapes, and under which
licence.
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import yaml

from slm_lab.contracts import static_cache
from slm_lab.evaluation.fixtures import canonical_json_sha256


DEFAULT_MODEL_CONTRACT = Path("configs/models/qwen3-0.6b.yaml")
DEFAULT_TOKEN_BUNDLE = Path("tests/fixtures/t10/token-fixtures-v1.json")
DEFAULT_WORKLOAD_CONFIG = Path("configs/workloads/t10-token-fixtures.json")
DEFAULT_EXPORT_CONTRACT = Path("configs/models/qwen3-0.6b-onnx-export.json")
DEFAULT_CALIBRATION_CONFIG = Path("configs/quantization/calibration.yaml")

SCHEMA_VERSION = 1
TASK_ID = "T40"
CORPUS_ID = "t40-qwen3-0.6b-t10-derived"
CORPUS_VERSION = "v1"
TIER_ONE_ID = "t10_derived"
TIER_TWO_ID = "external_diversity"
TIER_ONE_LICENSE = "CC0-1.0"
REPOSITORY_LICENSE = "Apache-2.0"

#: Every short fixture is tiled up to this length because it is the smallest
#: prompt length the T12 prefill contract defines. Padding is not an option:
#: the contract's ``attention_mask`` spec forbids it outright.
SHORT_FIXTURE_CONTEXT_LENGTH = 128

HF_DATASET_API = "https://huggingface.co/api/datasets/{dataset_id}"
EXTERNAL_VERIFIED_AT = "2026-08-02"

#: Tier-2 candidates. Every ``revision`` and ``license`` below was fetched from
#: the Hugging Face dataset API on ``EXTERNAL_VERIFIED_AT`` and can be re-checked
#: with ``python -m slm_lab.quantization.calibration verify --online``.
EXTERNAL_CANDIDATES: tuple[dict[str, Any], ...] = (
    {
        "id": "Salesforce/wikitext",
        "homepage": "https://huggingface.co/datasets/Salesforce/wikitext",
        "revision": "b08601e04326c79dfdd32d625aee71d232d685c3",
        "license": ["cc-by-sa-3.0", "gfdl"],
        "license_obligations": (
            "CC-BY-SA-3.0 requires attribution and is share-alike, so any "
            "committed derivative would have to be relicensed away from the "
            "repository's Apache-2.0 terms; GFDL adds invariant-section and "
            "copy-of-licence obligations."
        ),
        "data_committed": False,
        "assessment": (
            "Best-value candidate. Curated encyclopedic prose at the length "
            "scale the S1024 and S4096 workloads use, small enough to stream "
            "without a data pipeline, and already the de-facto reference for "
            "the perplexity T13 will report. Widens activation coverage "
            "beyond the single repeated seed T10 authored."
        ),
        "risk": (
            "Narrow register. Wikipedia-style prose alone under-covers the "
            "structured-output and chat control-token paths that tier 1 keeps."
        ),
    },
    {
        "id": "allenai/c4",
        "homepage": "https://huggingface.co/datasets/allenai/c4",
        "revision": "1588ec454efa1a09f29cd18ddd04fe05fc8653a2",
        "license": ["odc-by"],
        "license_obligations": (
            "ODC-BY requires attribution to the database producer and notice "
            "of the licence on any redistributed database or derivative "
            "database; it does not impose share-alike on the contents."
        ),
        "data_committed": False,
        "assessment": (
            "Widest register of the three: scraped web text carries markup "
            "residue, code fragments, and mixed scripts, which is the closest "
            "public proxy for the byte-fallback and punctuation-heavy token "
            "classes the raw canaries probe. The least burdensome licence of "
            "the three if a derivative ever had to be redistributed."
        ),
        "risk": (
            "Unfiltered quality and very large shard set. Selecting a "
            "reproducible slice needs its own pinned selection rule, which is "
            "T41 work, not T40 work."
        ),
    },
    {
        "id": "wikimedia/wikipedia",
        "homepage": "https://huggingface.co/datasets/wikimedia/wikipedia",
        "revision": "b04c8d1ceb2f5cd4588862100d08de323dccfbaa",
        "license": ["cc-by-sa-3.0", "gfdl"],
        "license_obligations": (
            "Same CC-BY-SA-3.0 attribution and share-alike obligations as "
            "wikitext, plus GFDL; a committed derivative could not stay "
            "Apache-2.0."
        ),
        "data_committed": False,
        "assessment": (
            "Only useful if multilingual coverage is wanted: the pre-parsed "
            "per-language configurations would exercise the multi-byte UTF-8 "
            "embedding rows the raw_unicode canary only samples. Largely "
            "redundant with wikitext for English-only calibration."
        ),
        "risk": (
            "Adds tens of gigabytes and the same share-alike obligations for "
            "coverage that overlaps wikitext; pick it only for a deliberate "
            "multilingual experiment."
        ),
    },
)

#: Why each committed T10 fixture is in the calibration corpus. A fixture with
#: no entry here is a hard error: T10 may not silently widen what T40 froze.
SELECTION_RATIONALE: dict[str, str] = {
    "S128": (
        "Shortest exported prefill shape (T20 S128, T12 cache capacity 160). "
        "Range observers must see the activations produced when the prompt "
        "matmuls are at their smallest sequence dimension and the KV cache is "
        "almost empty; a scale fitted only on long prompts over-covers this "
        "case and throws away INT8 resolution on the shape that decodes most "
        "often. This is a shape argument only: the four context workloads are "
        "nested token-ID prefixes of one another, so this sample adds no token "
        "class the longer three do not already carry."
    ),
    "S512": (
        "Mid-length exported prefill shape (cache capacity 576). Covers the "
        "regime between the short- and long-prompt extremes so that per-tensor "
        "scales are fitted on observed data rather than interpolated across an "
        "unobserved gap. Shape argument only; it is the S128 token IDs plus a "
        "continuation of the same repeated T10 seed."
    ),
    "S1024": (
        "Long exported prefill shape (cache capacity 1152). Attention-score "
        "and residual-stream magnitudes grow with sequence length, and this is "
        "the last shape before the 4096-token extreme. Shape argument only; it "
        "is the S512 token IDs plus a continuation of the same repeated seed."
    ),
    "S4096": (
        "Longest exported prefill shape (cache capacity 4224) and the worst "
        "case for activation range. Ranges fitted at 128 tokens do not bound "
        "the 4096-token case, so omitting it would guarantee clipping on "
        "exactly the shape T13 benchmarks hardest. Shape argument only; it is "
        "the S1024 token IDs plus a continuation of the same repeated seed, "
        "and it supplies 4096 of the corpus's token positions without widening "
        "the set of token IDs observed."
    ),
    "raw_ascii": (
        "ASCII letters and punctuation: the token class every deployed prompt "
        "contains. It puts that class in front of the range observers at the "
        "S128 shape. This is a presence claim about one token class, not a "
        "claim about vocabulary breadth; see coverage.distinct_token_ids for "
        "how few embedding rows the whole corpus actually touches."
    ),
    "raw_whitespace": (
        "Newlines, indentation, and runs of spaces tokenize into merged "
        "whitespace tokens that no prose sample in this corpus emits. "
        "Including them means the early-layer ranges are fitted with that "
        "token class present rather than on a prose-only distribution. "
        "Whether their activations differ, and by how much, is unmeasured "
        "until T41 runs an observer."
    ),
    "raw_unicode": (
        "Multilingual and non-Latin text drives multi-byte UTF-8 "
        "byte-fallback tokens, a token class the ASCII, whitespace, and "
        "structured canaries never produce. It is here so that class is "
        "present when the early-layer ranges are fitted. No claim is made "
        "about where its embedding rows sit or how large its activations are; "
        "neither has been measured."
    ),
    "raw_structured": (
        "JSON-like delimiters and quoted field names are the structured-output "
        "path the deployment actually serves. They concentrate on a small set "
        "of punctuation tokens that repeat at high frequency, which is "
        "expected to produce a different activation histogram from prose - "
        "expected, because no histogram has been measured anywhere in T40."
    ),
    "chat_non_thinking": (
        "The chat path renders control tokens (<|im_start|>, <|im_end|>, and "
        "the explicitly empty <think> block) that never appear on the "
        "raw-completion path. Their embeddings and the attention pattern "
        "around them are only observed if the chat canary is calibrated."
    ),
    "quality_arithmetic_sequence": (
        "One of the four CC0 prompts the W8/W4 quality delta is measured on in "
        "T41-T43. Calibration and evaluation inputs therefore overlap by "
        "design; see licensing.evaluation_overlap for why that is declared "
        "rather than hidden."
    ),
    "quality_cache_definition": (
        "One of the four CC0 prompts the W8/W4 quality delta is measured on in "
        "T41-T43. Calibration and evaluation inputs therefore overlap by "
        "design; see licensing.evaluation_overlap for why that is declared "
        "rather than hidden."
    ),
    "quality_timing_boundary": (
        "One of the four CC0 prompts the W8/W4 quality delta is measured on in "
        "T41-T43. Calibration and evaluation inputs therefore overlap by "
        "design; see licensing.evaluation_overlap for why that is declared "
        "rather than hidden."
    ),
    "quality_json_contract": (
        "One of the four CC0 prompts the W8/W4 quality delta is measured on in "
        "T41-T43. Calibration and evaluation inputs therefore overlap by "
        "design; see licensing.evaluation_overlap for why that is declared "
        "rather than hidden."
    ),
}

GENERATE_COMMAND = "uv run python -m slm_lab.quantization.calibration generate"
VERIFY_COMMAND = "uv run python -m slm_lab.quantization.calibration verify"
CHECK_COMMAND = "uv run python -m slm_lab.quantization.calibration check"
ONLINE_VERIFY_COMMAND = (
    "uv run python -m slm_lab.quantization.calibration verify --online"
)
CORPUS_HASH_COMMAND = (
    'python3 -c "import hashlib,json,yaml; '
    "c=yaml.safe_load(open('configs/quantization/calibration.yaml'))"
    "['calibration_corpus']; "
    "b=json.dumps(c,ensure_ascii=False,sort_keys=True,separators=(',',':'))"
    ".encode('utf-8'); "
    'print(hashlib.sha256(b).hexdigest())"'
)

FILE_HEADER = """\
# T40 calibration corpus contract for Qwen3-0.6B post-training quantization.
#
# GENERATED FILE. Do not hand-edit. Regenerate with:
#   uv run python -m slm_lab.quantization.calibration generate
# and verify with:
#   uv run python -m slm_lab.quantization.calibration check
#
# What a reader should take away
# ------------------------------
# 1. This file freezes the *inputs* to quantization, not any quantized result.
#    No weight is quantized here; AIMET is Linux + CUDA only and is specified
#    in environments/linux-aimet/, not executed on the development host.
# 2. Tier 1 (`calibration_corpus`) is the only tier that is committed and
#    required. Every one of its samples is derived deterministically from the
#    CC0-1.0 T10 token fixtures, so the corpus regenerates byte-for-byte from
#    material already in this repository with no heavy dependency and no
#    network access.
# 3. Coverage is argued, not assumed - and the arguments are bounded by
#    measurements. Every sample carries a `rationale` saying which deployment
#    behaviour it is there to expose: all four exported prefill shapes
#    (128/512/1024/4096) because activation ranges at 128 tokens do not bound
#    those at 4096; the four raw canaries because ASCII, whitespace, Unicode
#    byte-fallback, and structured punctuation are token classes that do not
#    substitute for one another; the chat canary because the chat template
#    emits control tokens the raw-completion path never produces; and the CC0
#    quality subset because that is what the quality delta is measured on.
#    Read `calibration_corpus.coverage` first: it is computed from the emitted
#    token IDs and states how narrow the corpus really is, including that the
#    four context workloads are nested prefixes of one repeated T10 seed. No
#    rationale here claims embedding-table or vocabulary coverage, and none may.
# 4. No sample is padded. The T12 prefill contract states that
#    `attention_mask` is "One for every real prompt token; padding is not
#    permitted." Short fixtures are therefore tiled to an exact frozen prompt
#    length instead of padded - see `calibration_corpus.preprocessing.padding`
#    and `.tiling` for the full argument.
# 5. Tier 2 is declared, never committed. The three public corpora below carry
#    their real repository revisions and their real card licences, fetched from
#    the Hugging Face dataset API. Their share-alike and attribution
#    obligations are why no row of them is in this repository, and why the
#    repository stays Apache-2.0 clean.
#
# The value T41+ must copy into every artifact manifest (plan section 17.4) is
# `calibration_dataset_revision`.
"""


class CalibrationValidationError(ValueError):
    """Raised when the calibration corpus or its provenance is inconsistent."""


@dataclass
class PlainTensor:
    """A dependency-free stand-in for a runtime tensor.

    Carries just enough surface (``dtype`` and ``shape``) for
    :func:`slm_lab.contracts.static_cache.validate_tensor_mapping` while holding
    its payload as ordinary nested Python lists, so calibration inputs can be
    materialized and contract-checked without numpy, torch, or onnxruntime.
    """

    name: str
    dtype: str
    shape: tuple[int, ...]
    values: list[list[int]]


@dataclass(frozen=True)
class CalibrationSample:
    """One frozen calibration sequence and the reason it exists."""

    sample_id: str
    tier: str
    source_group: str
    source_fixture_id: str
    interface: str
    construction: str
    source_token_count: int
    tile_repeats: int
    truncated: bool
    context_length: int
    cache_capacity: int
    token_ids: tuple[int, ...]
    source_token_ids_sha256: str
    rationale: str

    @property
    def token_count(self) -> int:
        """Return the emitted token count, which equals the context length."""

        return len(self.token_ids)

    def as_record(self) -> dict[str, Any]:
        """Return the committed manifest row for this sample.

        The token IDs themselves are deliberately *not* committed: they are
        already committed once in the T10 bundle, and duplicating them would
        create a second place for them to drift. The SHA-256 pins them.

        ``distinct_token_ids`` is measured from the emitted sequence so that a
        reader can see how narrow each sample is without re-deriving it, and so
        that the qualitative ``rationale`` can never be read as a coverage
        measurement.
        """

        return {
            "id": self.sample_id,
            "tier": self.tier,
            "source_group": self.source_group,
            "source_fixture_id": self.source_fixture_id,
            "interface": self.interface,
            "construction": self.construction,
            "source_token_count": self.source_token_count,
            "tile_repeats": self.tile_repeats,
            "truncated": self.truncated,
            "context_length": self.context_length,
            "cache_capacity": self.cache_capacity,
            "token_count": self.token_count,
            "distinct_token_ids": len(set(self.token_ids)),
            "source_token_ids_sha256": self.source_token_ids_sha256,
            "token_ids_sha256": canonical_json_sha256(list(self.token_ids)),
            "rationale": self.rationale,
        }


def _load_json(path: Path) -> Any:
    """Read *path* as JSON, converting every read failure into a clean error.

    A corrupt or unreadable input is a validation failure like any other, so it
    must reach the CLI as a ``CalibrationValidationError`` and exit 1 with an
    ``error:`` line rather than as a raw decoder traceback. Mirrors
    ``slm_lab.quantization.parity._load_json``. ``UnicodeDecodeError`` is caught
    alongside ``JSONDecodeError`` because the handle decodes lazily inside
    ``json.load``, and it is a ``ValueError`` the CLI would not otherwise catch.
    """

    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except OSError as exc:
        raise CalibrationValidationError(f"cannot read {path}: {exc}") from exc
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise CalibrationValidationError(f"cannot parse {path}: {exc}") from exc


def _load_yaml(path: Path) -> Any:
    """Read *path* as YAML with the same fail-closed contract as `_load_json`."""

    try:
        with path.open("r", encoding="utf-8") as handle:
            return yaml.safe_load(handle)
    except OSError as exc:
        raise CalibrationValidationError(f"cannot read {path}: {exc}") from exc
    except (yaml.YAMLError, UnicodeDecodeError) as exc:
        raise CalibrationValidationError(f"cannot parse {path}: {exc}") from exc


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise CalibrationValidationError(message)


def _tile_to_length(
    token_ids: Sequence[int],
    target_length: int,
    *,
    label: str,
) -> tuple[tuple[int, ...], int, bool]:
    """Repeat *token_ids* end to end and truncate to exactly *target_length*.

    Returns the emitted IDs, the number of whole source copies concatenated
    before truncation, and whether truncation actually discarded any token.
    """

    _require(len(token_ids) > 0, f"{label}: cannot tile an empty token sequence")
    _require(
        target_length > 0,
        f"{label}: target length must be positive, found {target_length}",
    )
    repeats = -(-target_length // len(token_ids))
    tiled = (list(token_ids) * repeats)[:target_length]
    truncated = repeats * len(token_ids) != target_length
    return tuple(tiled), repeats, truncated


def _rationale_for(fixture_id: str) -> str:
    try:
        return SELECTION_RATIONALE[fixture_id]
    except KeyError as exc:
        raise CalibrationValidationError(
            f"{fixture_id}: T10 fixture has no T40 selection rationale; "
            "a fixture may not enter the calibration corpus unattributed"
        ) from exc


def _validated_source_ids(
    record: Mapping[str, Any],
    *,
    vocab_size: int,
    label: str,
) -> tuple[int, ...]:
    token_ids = record.get("token_ids")
    _require(
        isinstance(token_ids, list) and len(token_ids) > 0,
        f"{label}: T10 record has no token IDs",
    )
    assert isinstance(token_ids, list)
    for token_id in token_ids:
        _require(
            isinstance(token_id, int) and not isinstance(token_id, bool),
            f"{label}: token IDs must be integers",
        )
        _require(
            0 <= token_id < vocab_size,
            f"{label}: token ID {token_id} outside model vocabulary [0, {vocab_size})",
        )
    _require(
        record.get("token_count") == len(token_ids),
        f"{label}: T10 token count drift",
    )
    _require(
        record.get("token_ids_sha256") == canonical_json_sha256(list(token_ids)),
        f"{label}: T10 token ID hash drift",
    )
    return tuple(token_ids)


def _ordered_source_records(
    bundle: Mapping[str, Any],
) -> list[tuple[str, Mapping[str, Any]]]:
    """Return T10 records in the declared, deterministic emission order."""

    for key in ("context_workloads", "raw_canaries", "chat_canary", "quality_subset"):
        _require(key in bundle, f"T10 bundle is missing {key!r}")

    contexts = sorted(
        bundle["context_workloads"],
        key=lambda record: int(record["context_length"]),
    )
    raw_canaries = sorted(bundle["raw_canaries"], key=lambda record: str(record["id"]))
    quality = sorted(bundle["quality_subset"], key=lambda record: str(record["id"]))

    ordered: list[tuple[str, Mapping[str, Any]]] = []
    ordered.extend(("context_workloads", record) for record in contexts)
    ordered.extend(("raw_canaries", record) for record in raw_canaries)
    ordered.append(("chat_canary", bundle["chat_canary"]))
    ordered.extend(("quality_subset", record) for record in quality)
    return ordered


def build_calibration_samples(
    bundle: Mapping[str, Any],
    model_contract: Mapping[str, Any],
) -> list[CalibrationSample]:
    """Derive every tier-1 calibration sample from the committed T10 bundle.

    Context workloads are used verbatim because their token counts already are
    frozen T12 prompt lengths. Every shorter fixture is tiled to the smallest
    frozen prompt length so that no emitted sequence ever needs padding.
    """

    vocab_size = int(model_contract["model"]["architecture"]["vocab_size"])
    _require(
        vocab_size == static_cache.VOCAB_SIZE,
        f"model contract vocabulary {vocab_size} differs from the T12 contract "
        f"value {static_cache.VOCAB_SIZE}",
    )

    samples: list[CalibrationSample] = []
    for index, (group, record) in enumerate(_ordered_source_records(bundle)):
        fixture_id = str(record["id"])
        label = f"{group}/{fixture_id}"
        source_ids = _validated_source_ids(
            record,
            vocab_size=vocab_size,
            label=label,
        )

        if group == "context_workloads":
            context_length = int(record["context_length"])
            _require(
                len(source_ids) == context_length,
                f"{label}: T10 context workload is not exactly {context_length} tokens",
            )
            token_ids, repeats, truncated = source_ids, 1, False
            construction = "verbatim"
        else:
            context_length = SHORT_FIXTURE_CONTEXT_LENGTH
            token_ids, repeats, truncated = _tile_to_length(
                source_ids,
                context_length,
                label=label,
            )
            construction = "tiled_then_truncated"

        _require(
            context_length in static_cache.CONTEXT_VARIANTS,
            f"{label}: context length {context_length} is not a frozen T12 "
            f"prompt length {tuple(static_cache.CONTEXT_VARIANTS)}",
        )
        samples.append(
            CalibrationSample(
                sample_id=f"cal-{index:02d}-{fixture_id}",
                tier=TIER_ONE_ID,
                source_group=group,
                source_fixture_id=fixture_id,
                interface=str(record["interface"]),
                construction=construction,
                source_token_count=len(source_ids),
                tile_repeats=repeats,
                truncated=truncated,
                context_length=context_length,
                cache_capacity=static_cache.CONTEXT_VARIANTS[context_length],
                token_ids=token_ids,
                source_token_ids_sha256=str(record["token_ids_sha256"]),
                rationale=_rationale_for(fixture_id),
            )
        )

    sample_ids = [sample.sample_id for sample in samples]
    _require(len(sample_ids) == len(set(sample_ids)), "calibration sample IDs collide")
    _require(
        sample_ids == sorted(sample_ids),
        "declared emission order is not ascending lexicographic by sample ID",
    )
    return samples


def build_prefill_tensors(sample: CalibrationSample) -> dict[str, PlainTensor]:
    """Materialize one sample as T12-conformant prefill input tensors.

    Every value is a plain Python ``int`` in a plain Python ``list``; nothing
    here needs numpy, torch, or onnxruntime. ``attention_mask`` is all ones by
    construction because the corpus never pads.
    """

    contract = static_cache.build_prefill_contract(sample.context_length)
    length = sample.token_count
    _require(
        length == sample.context_length,
        f"{sample.sample_id}: emitted {length} tokens for an "
        f"S{sample.context_length} prefill graph",
    )
    batch = static_cache.BATCH_SIZE
    tensors = {
        "input_ids": PlainTensor(
            name="input_ids",
            dtype=static_cache.TOKEN_DTYPE,
            shape=(batch, length),
            values=[list(sample.token_ids)],
        ),
        "attention_mask": PlainTensor(
            name="attention_mask",
            dtype=static_cache.MASK_DTYPE,
            shape=(batch, length),
            values=[[1] * length],
        ),
        "position_ids": PlainTensor(
            name="position_ids",
            dtype=static_cache.POSITION_DTYPE,
            shape=(batch, length),
            values=[list(range(length))],
        ),
    }
    static_cache.validate_tensor_mapping(tensors, contract.inputs)
    return tensors


def validate_prefill_tensors(sample: CalibrationSample) -> None:
    """Re-check one sample's emitted tensors against the frozen T12 contract.

    Be precise about what each half of this does.

    The mask and position assertions below are **construction post-conditions**,
    not independent checks. :func:`build_prefill_tensors` writes ``[1] * length``
    and ``list(range(length))`` a few lines earlier, so they can only fire if
    that function itself changes. "No sample is ever padded" is therefore
    guaranteed by *construction*; neither this function nor
    ``test_no_sample_is_ever_padded`` proves it about a tensor mapping this
    module did not build.

    The one genuinely independent failure this surfaces comes from
    :func:`build_prefill_tensors` itself: a token count that is not the graph's
    frozen prompt length, or a dtype or shape that
    :func:`slm_lab.contracts.static_cache.validate_tensor_mapping` rejects.
    """

    try:
        tensors = build_prefill_tensors(sample)
    except static_cache.CacheContractError as exc:
        raise CalibrationValidationError(
            f"{sample.sample_id}: prefill tensors violate the T12 contract: {exc}"
        ) from exc
    mask = tensors["attention_mask"].values[0]
    _require(
        all(value == 1 for value in mask),
        f"{sample.sample_id}: attention_mask contains a zero, which means the "
        "sample was padded; the T12 prefill contract forbids padding",
    )
    _require(
        tensors["position_ids"].values[0] == list(range(sample.token_count)),
        f"{sample.sample_id}: position_ids are not zero-based and contiguous",
    )


def build_preprocessing_contract(
    model_contract: Mapping[str, Any],
) -> dict[str, Any]:
    """Return the declarative, deterministic preprocessing contract."""

    tokens = model_contract["tokenizer"]["tokens"]
    return {
        "contract_module": "slm_lab.contracts.static_cache",
        "graph_kind": "prefill",
        "batch_size": static_cache.BATCH_SIZE,
        "batches": "one sample per batch; no sample is concatenated with another",
        "input_tensors": ["input_ids", "attention_mask", "position_ids"],
        "dtypes": {
            "input_ids": static_cache.TOKEN_DTYPE,
            "attention_mask": static_cache.MASK_DTYPE,
            "position_ids": static_cache.POSITION_DTYPE,
        },
        "frozen_prompt_lengths": sorted(static_cache.CONTEXT_VARIANTS),
        "ordering": {
            "rule": "ascending lexicographic sort of sample_id",
            "declared_emission_order": [
                "context_workloads ascending by context_length",
                "raw_canaries ascending by T10 fixture id",
                "chat_canary",
                "quality_subset ascending by T10 fixture id",
            ],
            "sample_id_format": "cal-{two-digit emission index}-{T10 fixture id}",
            "note": (
                "The numeric prefix makes the lexicographic sort identical to "
                "the declared emission order, so the ordering rule is one rule "
                "rather than two that can disagree."
            ),
        },
        "context_assignment": {
            "rule": (
                "Every sample is emitted at exactly one frozen T12 prompt "
                "length. A T10 context workload is already an exact frozen "
                "length and is used verbatim. Every shorter fixture is "
                "assigned to the smallest frozen prompt length, 128."
            ),
            "short_fixture_target_length": SHORT_FIXTURE_CONTEXT_LENGTH,
            "long_fixture_rule": "verbatim; token count already equals the shape",
            "no_committed_fixture_exceeds": max(static_cache.CONTEXT_VARIANTS),
        },
        "padding": {
            "policy": "forbidden",
            "attention_mask_value": 1,
            "reason": (
                "The T12 prefill contract defines attention_mask as 'One for "
                "every real prompt token; padding is not permitted.' Padding a "
                "calibration sample would therefore emit a tensor the exported "
                "graph does not accept, and would additionally teach the range "
                "observers the activation statistics of the pad embedding, "
                "which never occurs at inference."
            ),
            "pad_id_recorded_for_provenance_only": tokens["pad_id"],
            "eos_id_recorded_for_provenance_only": tokens["eos_id"],
        },
        "tiling": {
            "rule": (
                "Repeat the source T10 token-ID sequence end to end and "
                "truncate to the target length. Operates on token IDs, never "
                "on text, so no tokenizer is required to reproduce it."
            ),
            "applies_to": ["raw_canaries", "chat_canary", "quality_subset"],
            "precedent": (
                "T10 also reached its exact prompt lengths by repetition, but "
                "not by this construction. `_exact_context_record` in "
                "src/slm_lab/evaluation/fixtures.py joins copies of the "
                "authored seed *text* with a blank-line separator, tokenizes "
                "the joined text, truncates the IDs, decodes them back to "
                "text, re-encodes that text, and raises unless the round trip "
                "reproduces every ID. T40 deliberately drops both halves: it "
                "repeats token IDs directly, with no separator, and performs "
                "no decode/re-encode round trip. That is acceptable here "
                "because a calibration sample only has to present the range "
                "observers with real token IDs at a legal prefill shape, "
                "whereas a T10 fixture must be a prompt a tokenizer would "
                "actually emit. The cost is that a seam between two repeats "
                "may be an ID adjacency no string tokenizes to, which is "
                "exactly why a tiled sample is a calibration input only - see "
                "`boundary_note`."
            ),
            "boundary_note": (
                "Tiling makes a self-similar sequence. That is acceptable for "
                "fitting activation *ranges*, which depend on which token "
                "classes appear rather than on how natural the sequence reads, "
                "and it is the price of the no-padding rule. A tiled sample is "
                "a calibration input only; it must never be reused as a "
                "quality-evaluation prompt or as a latency workload."
            ),
        },
        "position_ids": {
            "rule": "zero-based ascending [0, prompt_length)",
        },
        "not_done": [
            "no shuffling: the emission order is fixed and declared",
            "no random sampling: every committed T10 fixture is used",
            "no seed: there is no randomness to seed",
            "no padding: forbidden by the T12 prefill contract",
            "no concatenation or packing of separate samples into one sequence",
            "no text-level preprocessing: the corpus is built from token IDs",
            "no third-party dataset row is read, downloaded, or committed",
        ],
    }


def build_coverage_measurements(
    samples: Sequence[CalibrationSample],
    *,
    vocab_size: int,
) -> dict[str, Any]:
    """Measure, rather than argue, how much of the input space the corpus sees.

    Every number here is computed from *samples* at generation time. The
    per-sample ``rationale`` strings are qualitative arguments about which token
    *classes* are present at which prefill shape; this block is the honest
    counterweight that keeps them from being read as coverage measurements.
    """

    distinct_overall: set[int] = set()
    per_group_ids: dict[str, set[int]] = {}
    per_group_tokens: dict[str, int] = {}
    for sample in samples:
        distinct_overall.update(sample.token_ids)
        per_group_ids.setdefault(sample.source_group, set()).update(sample.token_ids)
        per_group_tokens[sample.source_group] = (
            per_group_tokens.get(sample.source_group, 0) + sample.token_count
        )
    total_tokens = sum(per_group_tokens.values())

    contexts = sorted(
        (sample for sample in samples if sample.source_group == "context_workloads"),
        key=lambda sample: sample.context_length,
    )
    nested = all(
        longer.token_ids[: len(shorter.token_ids)] == shorter.token_ids
        for shorter, longer in zip(contexts, contexts[1:])
    )

    return {
        "measured_from": "the emitted tier-1 token IDs in this file",
        "distinct_token_ids": len(distinct_overall),
        "model_vocabulary_size": vocab_size,
        "vocabulary_fraction": round(len(distinct_overall) / vocab_size, 6),
        "distinct_token_ids_per_source_group": {
            group: len(ids) for group, ids in sorted(per_group_ids.items())
        },
        "token_share_per_source_group": {
            group: round(tokens / total_tokens, 4)
            for group, tokens in sorted(per_group_tokens.items())
        },
        "context_workloads_are_nested_prefixes": nested,
        "context_workload_chain": [f"S{sample.context_length}" for sample in contexts],
        "note": (
            "Read this block before reading any `rationale`. Two facts limit "
            "what the corpus can support. First, the four context workloads "
            "are token-ID prefixes of one another in ascending length order, "
            "because T10 built all four by repeating one authored seed; they "
            "are four *shape* arguments over one body of text, not four "
            "independent content arguments, and `token_share_per_source_group` "
            "shows how much of the token budget that one body of text "
            "consumes. Second, the corpus touches `distinct_token_ids` of the "
            f"{vocab_size} embedding rows in the model. No sample selection "
            "here should be read as covering the embedding table, the "
            "vocabulary, or any activation distribution; the only coverage "
            "argued is over deployment shapes and over the presence of a few "
            "named token classes. Widening it is tier-2 work owned by T41."
        ),
    }


def build_corpus(
    bundle: Mapping[str, Any],
    model_contract: Mapping[str, Any],
) -> dict[str, Any]:
    """Build the tier-1 corpus document whose canonical JSON is hashed.

    This mapping is exactly the payload behind
    ``calibration_corpus_canonical_json_sha256``. It contains everything that
    determines the calibration inputs - the source revision, the preprocessing
    contract, and the sample table - and nothing that does not, so a licence
    note or a prose edit elsewhere in the file never changes the corpus
    revision.
    """

    samples = build_calibration_samples(bundle, model_contract)
    vocab_size = int(model_contract["model"]["architecture"]["vocab_size"])
    per_context: dict[str, int] = {}
    per_group: dict[str, int] = {}
    for sample in samples:
        key = f"S{sample.context_length}"
        per_context[key] = per_context.get(key, 0) + sample.token_count
        per_group[sample.source_group] = (
            per_group.get(sample.source_group, 0) + sample.token_count
        )
    total_tokens = sum(sample.token_count for sample in samples)

    return {
        "schema_version": SCHEMA_VERSION,
        "task_id": TASK_ID,
        "corpus_id": CORPUS_ID,
        "corpus_version": CORPUS_VERSION,
        "tier": TIER_ONE_ID,
        "status": "required_and_committed",
        "license": TIER_ONE_LICENSE,
        "source_bundle": {
            "path": DEFAULT_TOKEN_BUNDLE.as_posix(),
            "canonical_json_sha256": canonical_json_sha256(bundle),
            "license": bundle["license"],
        },
        "preprocessing": build_preprocessing_contract(model_contract),
        "token_budget": {
            "sample_count": len(samples),
            "total_calibration_tokens": total_tokens,
            "tokens_per_prompt_shape": {
                f"S{length}": per_context[f"S{length}"]
                for length in sorted(static_cache.CONTEXT_VARIANTS)
                if f"S{length}" in per_context
            },
            "tokens_per_source_group": dict(sorted(per_group.items())),
            "note": (
                "Token budget is the number of token positions the range "
                "observers see, not a wall-clock cost. It is small on purpose: "
                "the corpus is a coverage argument over deployment shapes and "
                "token classes, not a statistical sample of natural text. "
                "Widening it is tier-2 work owned by T41."
            ),
        },
        "coverage": build_coverage_measurements(samples, vocab_size=vocab_size),
        "samples": [sample.as_record() for sample in samples],
    }


def calibration_dataset_revision(corpus_sha256: str) -> str:
    """Return the manifest value T41+ copies into every artifact manifest."""

    _require(
        len(corpus_sha256) == 64,
        f"corpus hash must be a 64-character SHA-256, found {corpus_sha256!r}",
    )
    return f"{CORPUS_ID}-{CORPUS_VERSION}+sha256.{corpus_sha256[:16]}"


def build_external_candidates() -> dict[str, Any]:
    """Return the declared, never-committed tier-2 candidate table."""

    return {
        "tier": TIER_TWO_ID,
        "status": "declared_candidate",
        "selection_owner": "T41",
        "data_committed": False,
        "purpose": (
            "Widen activation coverage beyond the single authored T10 seed and "
            "remove the tier-1 overlap between calibration and evaluation "
            "prompts. None of these is used by T40; they are recorded so that "
            "T41 chooses from a revision-pinned, licence-checked list instead "
            "of an ad-hoc download."
        ),
        "verification": {
            "api_url_template": HF_DATASET_API,
            "verified_at": EXTERNAL_VERIFIED_AT,
            "command": ONLINE_VERIFY_COMMAND,
            "fields_verified": ["sha", "cardData.license"],
        },
        "candidates": [dict(candidate) for candidate in EXTERNAL_CANDIDATES],
    }


def build_licensing(bundle: Mapping[str, Any]) -> dict[str, Any]:
    """Return the licensing block for the calibration contract."""

    return {
        "repository_license": REPOSITORY_LICENSE,
        "model_license": "Apache-2.0",
        "tier_1_license": TIER_ONE_LICENSE,
        "tier_1_basis": (
            "Tier 1 is a deterministic token-ID transformation of the T10 "
            "fixtures, which were authored for this repository and released "
            "CC0-1.0. No third-party text enters the corpus, so the derived "
            "corpus inherits CC0-1.0 and is compatible with the Apache-2.0 "
            "repository."
        ),
        "tier_2_obligations": [
            (
                "CC-BY-SA-3.0 (Salesforce/wikitext, wikimedia/wikipedia) "
                "requires attribution and is share-alike: a committed "
                "derivative would have to be relicensed away from Apache-2.0."
            ),
            (
                "GFDL (Salesforce/wikitext, wikimedia/wikipedia) adds "
                "copy-of-licence and invariant-section obligations on "
                "redistribution."
            ),
            (
                "ODC-BY (allenai/c4) requires attribution to the database "
                "producer and a notice of the licence on any redistributed "
                "database or derivative database."
            ),
        ],
        "third_party_rows_committed": False,
        "third_party_rows_statement": (
            "No row, excerpt, or tokenization of any tier-2 dataset is "
            "committed to this repository. Only dataset identifiers, "
            "repository revisions, and licence metadata are recorded. That is "
            "why the repository remains Apache-2.0 clean while still pinning "
            "exactly what a future calibration run would read."
        ),
        "evaluation_overlap": {
            "overlaps": True,
            "scope": "quality_subset (4 of 13 tier-1 samples)",
            "statement": (
                "The four CC0 quality prompts are both calibrated on and "
                "evaluated on. This is deliberate - the observers should see "
                "the distribution the delta is measured on - but it biases the "
                "measured quality delta optimistically, because the quantized "
                "model's ranges were fitted on the evaluation inputs. T41-T43 "
                "must report this overlap alongside any quality number, and "
                "must not present the delta as evidence of generalization. "
                "Admitting a tier-2 corpus is the way to remove the overlap."
            ),
        },
    }


def build_document(
    *,
    bundle: Mapping[str, Any],
    workload_config: Mapping[str, Any],
    model_contract: Mapping[str, Any],
    export_contract: Mapping[str, Any],
) -> dict[str, Any]:
    """Build the full committed calibration contract document."""

    corpus = build_corpus(bundle, model_contract)
    corpus_sha256 = canonical_json_sha256(corpus)
    architecture = model_contract["model"]["architecture"]
    tokenizer = model_contract["tokenizer"]

    return {
        "schema_version": SCHEMA_VERSION,
        "task_id": TASK_ID,
        "title": "Qwen3-0.6B post-training-quantization calibration contract",
        "summary": (
            "Frozen calibration inputs for the Lane B W8/W4/LPBQ/LiteMP "
            "experiments (plan section 7.2, Q1-Q5). Tier 1 is committed, "
            "CC0-1.0, and regenerates offline from the T10 token fixtures; "
            "tier 2 is a declared, revision-pinned candidate list that is "
            "never committed. No quantized result is claimed here."
        ),
        "model": {
            "id": model_contract["model"]["id"],
            "revision": model_contract["model"]["revision"],
            "license": model_contract["model"]["license"],
            "reference_dtype": model_contract["model"]["reference_dtype"],
            "vocab_size": architecture["vocab_size"],
            "num_hidden_layers": architecture["num_hidden_layers"],
            "num_key_value_heads": architecture["num_key_value_heads"],
        },
        "tokenizer": {
            "id": tokenizer["id"],
            "revision": tokenizer["revision"],
            "class": tokenizer["class"],
            "add_bos_token": tokenizer["add_bos_token"],
            "pad_id": tokenizer["tokens"]["pad_id"],
            "eos_id": tokenizer["tokens"]["eos_id"],
            "chat_template_sha256": tokenizer["chat_template"]["sha256"],
        },
        "graph_contract": {
            "owner_task": "T12",
            "module": "slm_lab.contracts.static_cache",
            "graph_kind": "prefill",
            "prompt_length_to_cache_capacity": {
                f"S{prompt_length}": capacity
                for prompt_length, capacity in sorted(
                    static_cache.CONTEXT_VARIANTS.items()
                )
            },
            "note": (
                "Calibration only exercises the prefill graph. The decode "
                "graph consumes a materialized KV cache, so its activation "
                "ranges are a function of the prefill ranges plus the decode "
                "step itself; T41 owns whether a decode-side observer pass is "
                "needed."
            ),
        },
        "inputs": [
            {
                "path": DEFAULT_TOKEN_BUNDLE.as_posix(),
                "role": "tier-1 calibration source (T10 token fixtures)",
                "canonical_json_sha256": canonical_json_sha256(bundle),
            },
            {
                "path": DEFAULT_WORKLOAD_CONFIG.as_posix(),
                "role": "T10 workload manifest; pins the bundle hash",
                "canonical_json_sha256": canonical_json_sha256(workload_config),
            },
            {
                "path": DEFAULT_MODEL_CONTRACT.as_posix(),
                "role": "T00 model/tokenizer identity and vocabulary size",
                "canonical_json_sha256": canonical_json_sha256(model_contract),
            },
            {
                "path": DEFAULT_EXPORT_CONTRACT.as_posix(),
                "role": "T20 ONNX export pins; fixes the shapes calibrated here",
                "canonical_json_sha256": canonical_json_sha256(export_contract),
            },
        ],
        "calibration_corpus": corpus,
        "calibration_corpus_canonical_json_sha256": corpus_sha256,
        "calibration_dataset_revision": calibration_dataset_revision(corpus_sha256),
        "external_diversity_candidates": build_external_candidates(),
        "licensing": build_licensing(bundle),
        "artifact_manifest_contract": {
            "plan_section": "17.4",
            "field": "calibration_dataset_revision",
            "value": calibration_dataset_revision(corpus_sha256),
            "instruction": (
                "Every T41+ artifact manifest that reports a quantized result "
                "must carry this exact string. A manifest whose "
                "calibration_dataset_revision does not match the value this "
                "file regenerates was produced against a different corpus and "
                "its quality delta is not comparable."
            ),
        },
        "commands": {
            "generate": GENERATE_COMMAND,
            "verify": VERIFY_COMMAND,
            "verify_online": ONLINE_VERIFY_COMMAND,
            "check": CHECK_COMMAND,
            "recompute_corpus_hash": CORPUS_HASH_COMMAND,
            "tests": "uv run pytest tests/quantization",
        },
    }


def render_document(document: Mapping[str, Any]) -> str:
    """Render the calibration contract as deterministic, commented YAML."""

    body = yaml.safe_dump(
        dict(document),
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=76,
    )
    return FILE_HEADER + "\n" + body


def _validate_external_candidates(recorded: Mapping[str, Any]) -> None:
    _require(
        recorded.get("data_committed") is False,
        "tier-2 candidates must declare data_committed: false",
    )
    candidates = recorded.get("candidates")
    _require(
        isinstance(candidates, list) and len(candidates) > 0,
        "tier-2 candidate list is empty",
    )
    assert isinstance(candidates, list)
    for candidate in candidates:
        dataset_id = candidate.get("id", "<missing id>")
        _require(
            candidate.get("data_committed") is False,
            f"{dataset_id}: tier-2 dataset rows may not be committed",
        )
        revision = candidate.get("revision")
        _require(
            isinstance(revision, str)
            and len(revision) == 40
            and all(character in "0123456789abcdef" for character in revision),
            f"{dataset_id}: tier-2 revision must be a full 40-hex commit SHA",
        )
        licenses = candidate.get("license")
        _require(
            isinstance(licenses, list)
            and len(licenses) > 0
            and all(isinstance(name, str) and name.strip() for name in licenses),
            f"{dataset_id}: tier-2 licence must be a non-empty list of names",
        )
        _require(
            bool(str(candidate.get("license_obligations", "")).strip()),
            f"{dataset_id}: tier-2 licence obligations must be stated",
        )
    _require(
        recorded == build_external_candidates(),
        "tier-2 candidate table differs from the pinned, fetched values",
    )


def validate_documents(
    *,
    config: Mapping[str, Any],
    bundle: Mapping[str, Any],
    workload_config: Mapping[str, Any],
    model_contract: Mapping[str, Any],
    export_contract: Mapping[str, Any],
) -> None:
    """Validate the calibration contract against every committed input."""

    _require(
        config.get("schema_version") == SCHEMA_VERSION,
        "calibration contract: unsupported schema version",
    )
    _require(
        config.get("task_id") == TASK_ID,
        "calibration contract: unexpected task ID",
    )

    bundle_sha256 = canonical_json_sha256(bundle)
    expected_input_hashes = {
        DEFAULT_TOKEN_BUNDLE.as_posix(): bundle_sha256,
        DEFAULT_WORKLOAD_CONFIG.as_posix(): canonical_json_sha256(workload_config),
        DEFAULT_MODEL_CONTRACT.as_posix(): canonical_json_sha256(model_contract),
        DEFAULT_EXPORT_CONTRACT.as_posix(): canonical_json_sha256(export_contract),
    }
    recorded_inputs = config.get("inputs")
    _require(
        isinstance(recorded_inputs, list) and len(recorded_inputs) == 4,
        "calibration contract must record all four committed inputs",
    )
    assert isinstance(recorded_inputs, list)
    for entry in recorded_inputs:
        path = entry.get("path")
        _require(
            path in expected_input_hashes,
            f"calibration contract records an unknown input {path!r}",
        )
        _require(
            entry.get("canonical_json_sha256") == expected_input_hashes[path],
            f"{path}: recorded input hash drift",
        )

    corpus = config.get("calibration_corpus")
    _require(
        isinstance(corpus, Mapping),
        "calibration contract has no calibration_corpus block",
    )
    assert isinstance(corpus, Mapping)
    _require(
        corpus.get("source_bundle", {}).get("canonical_json_sha256") == bundle_sha256,
        "T10 token bundle hash drift: the frozen calibration source is not the "
        "bundle this repository commits",
    )

    expected_corpus = build_corpus(bundle, model_contract)
    _require(
        corpus.get("preprocessing") == expected_corpus["preprocessing"],
        "preprocessing contract drift",
    )
    _require(
        corpus.get("coverage") == expected_corpus["coverage"],
        "coverage measurement drift: the recorded coverage figures are not the "
        "ones measured from the emitted samples",
    )

    recorded_samples = corpus.get("samples")
    expected_samples = expected_corpus["samples"]
    _require(
        isinstance(recorded_samples, list),
        "calibration corpus has no sample table",
    )
    assert isinstance(recorded_samples, list)
    _require(
        len(recorded_samples) == len(expected_samples),
        f"calibration sample count drift: recorded {len(recorded_samples)}, "
        f"derived {len(expected_samples)}",
    )
    for recorded, expected in zip(recorded_samples, expected_samples, strict=True):
        label = recorded.get("id", "<missing id>")
        _require(
            recorded.get("id") == expected["id"],
            f"calibration sample ordering drift at {label!r}",
        )
        _require(
            recorded.get("token_count") == expected["token_count"],
            f"{label}: token count drift",
        )
        _require(
            recorded.get("context_length") == expected["context_length"],
            f"{label}: context assignment drift",
        )
        _require(
            recorded.get("token_ids_sha256") == expected["token_ids_sha256"],
            f"{label}: emitted token ID hash drift",
        )
        _require(
            recorded == expected,
            f"{label}: calibration sample record drift",
        )

    budget = corpus.get("token_budget", {})
    total = sum(int(sample["token_count"]) for sample in recorded_samples)
    _require(
        budget.get("total_calibration_tokens") == total,
        f"token budget drift: recorded "
        f"{budget.get('total_calibration_tokens')}, samples sum to {total}",
    )
    _require(
        budget.get("sample_count") == len(recorded_samples),
        "token budget sample count drift",
    )

    corpus_sha256 = canonical_json_sha256(corpus)
    _require(
        config.get("calibration_corpus_canonical_json_sha256") == corpus_sha256,
        "calibration corpus hash drift",
    )
    _require(
        corpus_sha256 == canonical_json_sha256(expected_corpus),
        "calibration corpus differs from the corpus derived from committed inputs",
    )
    expected_revision = calibration_dataset_revision(corpus_sha256)
    _require(
        config.get("calibration_dataset_revision") == expected_revision,
        f"calibration_dataset_revision drift: expected {expected_revision}",
    )
    _require(
        config.get("artifact_manifest_contract", {}).get("value") == expected_revision,
        "artifact manifest calibration_dataset_revision drift",
    )

    external = config.get("external_diversity_candidates")
    _require(
        isinstance(external, Mapping),
        "calibration contract has no tier-2 candidate block",
    )
    assert isinstance(external, Mapping)
    _validate_external_candidates(external)

    licensing = config.get("licensing", {})
    _require(
        licensing.get("repository_license") == REPOSITORY_LICENSE,
        "licensing: repository licence drift",
    )
    _require(
        licensing.get("tier_1_license") == TIER_ONE_LICENSE,
        "licensing: tier-1 licence drift",
    )
    _require(
        bundle.get("license") == TIER_ONE_LICENSE,
        "licensing: the T10 source bundle is no longer CC0-1.0",
    )
    _require(
        licensing.get("third_party_rows_committed") is False,
        "licensing: third-party dataset rows may not be committed",
    )

    for sample in build_calibration_samples(bundle, model_contract):
        validate_prefill_tensors(sample)

    expected_document = build_document(
        bundle=bundle,
        workload_config=workload_config,
        model_contract=model_contract,
        export_contract=export_contract,
    )
    _require(
        dict(config) == expected_document,
        "committed calibration contract differs from the derived contract",
    )


def load_inputs(repo_root: Path) -> dict[str, Any]:
    """Load every committed document the calibration contract depends on."""

    return {
        "bundle": _load_json(repo_root / DEFAULT_TOKEN_BUNDLE),
        "workload_config": _load_json(repo_root / DEFAULT_WORKLOAD_CONFIG),
        # `configs/models/qwen3-0.6b.yaml` is JSON-formatted despite its
        # extension, and the repository reads it with `json.loads` everywhere
        # else (`evaluation/fixtures.py`, `models/qwen3_reference.py`,
        # `export/onnx_matrix.py`, `backends/mlx_baseline.py`,
        # `quantization/parity.py`). Follow that convention rather than
        # accepting a YAML superset this contract's producers never emit.
        "model_contract": _load_json(repo_root / DEFAULT_MODEL_CONTRACT),
        "export_contract": _load_json(repo_root / DEFAULT_EXPORT_CONTRACT),
    }


def validate_repository(repo_root: Path) -> None:
    """Validate the committed calibration contract rooted at *repo_root*."""

    config_path = repo_root / DEFAULT_CALIBRATION_CONFIG
    if not config_path.is_file():
        raise CalibrationValidationError(
            f"calibration contract is missing: {config_path}"
        )
    inputs = load_inputs(repo_root)
    config = _load_yaml(config_path)
    if not isinstance(config, Mapping):
        raise CalibrationValidationError(
            f"calibration contract is not a YAML mapping: {config_path}"
        )
    validate_documents(config=config, **inputs)

    expected_text = render_document(
        build_document(
            bundle=inputs["bundle"],
            workload_config=inputs["workload_config"],
            model_contract=inputs["model_contract"],
            export_contract=inputs["export_contract"],
        )
    )
    if config_path.read_text(encoding="utf-8") != expected_text:
        raise CalibrationValidationError(
            "committed calibration contract is not byte-identical to a fresh "
            f"regeneration; run: {GENERATE_COMMAND}"
        )


def generate_repository(repo_root: Path) -> Path:
    """Regenerate the committed calibration contract and return its path."""

    inputs = load_inputs(repo_root)
    document = build_document(
        bundle=inputs["bundle"],
        workload_config=inputs["workload_config"],
        model_contract=inputs["model_contract"],
        export_contract=inputs["export_contract"],
    )
    config_path = repo_root / DEFAULT_CALIBRATION_CONFIG
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(render_document(document), encoding="utf-8")
    return config_path


def fetch_dataset_metadata(dataset_id: str, *, timeout: float = 20.0) -> dict[str, Any]:
    """Fetch one Hugging Face dataset's revision and card licence.

    Only used by ``verify --online``. Never called from tests, which must stay
    offline and deterministic.
    """

    url = HF_DATASET_API.format(dataset_id=dataset_id)
    try:
        with urllib.request.urlopen(url, timeout=timeout) as response:  # noqa: S310
            payload = json.load(response)
    except (urllib.error.URLError, TimeoutError, ValueError) as exc:
        raise CalibrationValidationError(
            f"{dataset_id}: could not fetch {url}: {exc}"
        ) from exc
    return {
        "sha": payload.get("sha"),
        "license": (payload.get("cardData") or {}).get("license"),
    }


def verify_external_candidates_online(
    candidates: Iterable[Mapping[str, Any]] = EXTERNAL_CANDIDATES,
) -> None:
    """Re-fetch every tier-2 revision and licence and fail closed on drift."""

    for candidate in candidates:
        dataset_id = str(candidate["id"])
        upstream = fetch_dataset_metadata(dataset_id)
        _require(
            upstream["sha"] == candidate["revision"],
            f"{dataset_id}: upstream revision is {upstream['sha']}, "
            f"pinned revision is {candidate['revision']}",
        )
        _require(
            upstream["license"] == candidate["license"],
            f"{dataset_id}: upstream licence is {upstream['license']}, "
            f"pinned licence is {candidate['license']}",
        )


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse calibration CLI arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser(
        "generate",
        help="rewrite configs/quantization/calibration.yaml from committed inputs",
    )
    verify = subparsers.add_parser(
        "verify",
        help="full offline validation; identical to `check` unless --online",
    )
    verify.add_argument(
        "--online",
        action="store_true",
        help=(
            "additionally re-fetch tier-2 dataset revisions and licences from "
            "the HF API; the only behaviour `check` cannot perform"
        ),
    )
    subparsers.add_parser(
        "check",
        help="full offline validation; identical to `verify` without --online, "
        "and the CI gate because it cannot reach the network",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Run the calibration corpus CLI."""

    args = parse_args(argv)
    repo_root = args.repo_root.resolve()
    try:
        if args.command == "generate":
            path = generate_repository(repo_root)
            print(f"wrote {path}")
        else:
            validate_repository(repo_root)
            if args.command == "verify" and args.online:
                verify_external_candidates_online()
    except (
        CalibrationValidationError,
        static_cache.CacheContractError,
        OSError,
    ) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(f"T40 calibration corpus {args.command} passed: {repo_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
