"""Tests for the T23 reference-graph numeric-claim audit.

Every test drives the tool from synthetic fixtures rather than from the live
repository, because the evidence files the tool reads are regenerated by the
export pipeline and would make these assertions move under the tests.
"""

from __future__ import annotations

import hashlib
import importlib.util
import io
import json
import os
import subprocess
import sys
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Dict, List, Optional, Sequence
from unittest import mock

REPO_ROOT = Path(__file__).resolve().parents[2]
TOOL_PATH = REPO_ROOT / "scripts" / "audit" / "audit_reference_graph_claims.py"


def _load_tool():
    spec = importlib.util.spec_from_file_location("audit_tool", TOOL_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot import {TOOL_PATH}")
    module = importlib.util.module_from_spec(spec)
    # Registered before execution so `dataclasses` can resolve the module's own
    # annotations on Python 3.9.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


audit = _load_tool()


# --------------------------------------------------------------------------
# Fixtures
# --------------------------------------------------------------------------

VARIANTS = ("S128", "S512")


class DictReader(audit.Reader):
    """An in-memory snapshot of a repository."""

    def __init__(self, files: Dict[str, str], name: str = "fixture") -> None:
        self.files = {k: v.encode("utf-8") for k, v in files.items()}
        self.name = name

    def read_bytes(self, relpath: str) -> Optional[bytes]:
        return self.files.get(relpath)

    def paths(self) -> Sequence[str]:
        return sorted(self.files)


def _digest(seed: str) -> str:
    return hashlib.sha256(seed.encode("utf-8")).hexdigest()


def evidence_files(
    *,
    prefill_nodes: int,
    prefill_pad: Optional[int],
    prefill_bytes: Dict[str, int],
    prefill_seed: str,
    shape_denominator: int,
    prefill_constant_of_shape: int,
) -> Dict[str, str]:
    """One coherent, fully regenerated evidence set."""
    files: Dict[str, str] = {}
    graph_digest = {
        variant: {
            "prefill": _digest(f"{prefill_seed}-{variant}-prefill"),
            "decode": _digest(f"decode-{variant}"),
        }
        for variant in VARIANTS
    }
    files["configs/models/qwen3-0.6b-onnx-export.json"] = json.dumps({
        "contexts": [128, 512],
        "packages": {"torch": "2.7.1"},
        "export": {"opset": 18},
        "evidence_attestation": {
            "run_id": "fixture-run",
            "runtime_python_version": "3.11.13",
            "external_data_sha256": _digest("external"),
            "source_artifact_sha256": _digest("source"),
            "graph_sha256": graph_digest,
        },
    }, indent=1)
    files["configs/models/qwen3-0.6b.yaml"] = json.dumps({
        "model": {"architecture": {"num_hidden_layers": 28}}
    }, indent=1)

    prefill_ops = {"Cast": 460, "MatMul": 254,
                   "ConstantOfShape": prefill_constant_of_shape,
                   "Shape": 121, "Concat": 341}
    if prefill_pad is not None:
        prefill_ops["Pad"] = prefill_pad
    decode_ops = {"Cast": 464, "MatMul": 254, "ConstantOfShape": 91,
                  "Shape": 459, "Concat": 370, "ScatterElements": 56}

    for variant in VARIANTS:
        files[f"results/manifests/onnx/{variant}.json"] = json.dumps({
            "variant_id": variant,
            "cache_capacity": 160 if variant == "S128" else 576,
            "context_length": int(variant[1:]),
            "created_at": "2026-08-02T00:00:00Z",
            "artifacts": {
                "prefill": {
                    "relative_path": f"{variant}/prefill.onnx",
                    "sha256": graph_digest[variant]["prefill"],
                    "size_bytes": prefill_bytes[variant],
                    "external_data": [
                        {"sha256": _digest("external"),
                         "size_bytes": 1192085504}
                    ],
                },
                "decode": {
                    "relative_path": f"{variant}/decode.onnx",
                    "sha256": graph_digest[variant]["decode"],
                    "size_bytes": 1759947,
                    "external_data": [
                        {"sha256": _digest("external"),
                         "size_bytes": 1192085504}
                    ],
                },
            },
        }, indent=1)

        def graph(kind: str, ops: Dict[str, int], nodes: int) -> dict:
            return {
                "graph_kind": kind,
                "variant_id": variant,
                "node_count": nodes,
                "input_count": 3 if kind == "prefill" else 60,
                "output_count": 58,
                "initializer_count": 310,
                "external_initializer_count": 254,
                "largest_inline_initializer_bytes": 256,
                "ir_version": 8,
                "dynamic_dimensions": [],
                "finding_count": 2,
                "source_sha256": graph_digest[variant][kind],
                "op_histogram": ops,
                "opset_imports": [["", 18]],
                "findings": [
                    {
                        "rule_id": "R-DATA-DEPENDENT-SHAPE-INPUT",
                        "count": 804 if kind == "prefill" else 1231,
                        "detail": (
                            f"{804 if kind == 'prefill' else 1231} of "
                            f"{shape_denominator if kind == 'prefill' else 1326}"
                            " shape-defining operator inputs are computed"
                        ),
                    },
                    {
                        "rule_id": "R-WIDE-IO-BOUNDARY",
                        "count": 58 if kind == "prefill" else 118,
                        "detail": "graph boundary is wide",
                    },
                    {
                        "rule_id": "R-GRAPH-NODE-COUNT",
                        "count": nodes,
                        "detail": f"the graph carries {nodes} nodes",
                    },
                ],
            }

        files[f"results/graph/{variant}.json"] = json.dumps({
            "context_length": int(variant[1:]),
            "cache_capacity": 160 if variant == "S128" else 576,
            "generated_by": {"rules_sha256": _digest("rules")},
            "graphs": {
                "prefill": graph("prefill", prefill_ops, prefill_nodes),
                "decode": graph("decode", decode_ops, 10191),
            },
        }, indent=1)

        files[f"results/graph/parity/{variant}-ort-cpu.json"] = json.dumps({
            "prompt_length": int(variant[1:]),
            "steps_requested": 4,
            "tolerance": {"atol": 0.25},
            "runtime": {"onnxruntime_version": "1.28.0",
                        "python_version": "3.11.13"},
            "graph_digests": {
                kind: {"relative_path": f"{variant}/{kind}.onnx",
                       "sha256": graph_digest[variant][kind]}
                for kind in ("prefill", "decode")
            },
            "steps": [],
        }, indent=1)
    return files


PRE = dict(prefill_nodes=8753, prefill_pad=56,
           prefill_bytes={"S128": 1560358, "S512": 2064360},
           prefill_seed="pad", shape_denominator=1257,
           prefill_constant_of_shape=118)
POST = dict(prefill_nodes=7634, prefill_pad=None,
            prefill_bytes={"S128": 1600000, "S512": 2100000},
            prefill_seed="concat", shape_denominator=922,
            prefill_constant_of_shape=62)


def document(text: str) -> Dict[str, str]:
    return {"docs/results/onnx/graph-inspection.md": text}


class AuditFixture:
    """A pre/post pair of evidence snapshots plus a document under review."""

    def __init__(self, doc_text: str, post: bool = True) -> None:
        pre_files = evidence_files(**PRE)
        post_files = evidence_files(**POST)
        current_files = dict(post_files if post else pre_files)
        current_files.update(document(doc_text))
        self.doc_path = "docs/results/onnx/graph-inspection.md"
        self.doc_text = doc_text
        self.current = audit.harvest(DictReader(current_files, "current"))
        self.baseline = audit.harvest(DictReader(pre_files, "baseline"))
        self.classifier = audit.Classifier(self.current, self.baseline)
        self.tokens = audit.tokenize(
            self.doc_path, "reconcile", doc_text,
            self.classifier.known_digests(),
        )

    def buckets(self) -> Dict[str, List]:
        out: Dict[str, List] = {
            "MOVES": [], "STATIC": [], "AMBIGUOUS": [], "UNCLASSIFIED": []}
        for token in self.tokens:
            bucket, meanings = self.classifier.classify(token)
            out[bucket].append((token, meanings))
        return out

    def bucket_of(self, literal: str) -> str:
        for token in self.tokens:
            if token.raw == literal:
                return self.classifier.classify(token)[0]
        raise AssertionError(f"literal {literal!r} was never tokenized")

    def meanings_of(self, literal: str):
        for token in self.tokens:
            if token.raw == literal:
                return self.classifier.classify(token)[1]
        raise AssertionError(f"literal {literal!r} was never tokenized")

    def pre_digest(self, variant: str, kind: str) -> str:
        return _digest(f"pad-{variant}-{kind}") if kind == "prefill" \
            else _digest(f"decode-{variant}")

    def post_digest(self, variant: str, kind: str) -> str:
        return _digest(f"concat-{variant}-{kind}") if kind == "prefill" \
            else _digest(f"decode-{variant}")


# --------------------------------------------------------------------------
# Tokenizing
# --------------------------------------------------------------------------


class TokenizerTests(unittest.TestCase):
    def tokens(self, text: str, digests: Sequence[str] = ()):
        return audit.tokenize("d.md", "reconcile", text, digests)

    def test_thousands_separators_are_one_token(self) -> None:
        tokens = self.tokens("the graph has 8,753 nodes")
        self.assertEqual([t.raw for t in tokens], ["8,753"])
        self.assertEqual(tokens[0].integral, 8753)

    def test_trailing_comma_is_not_part_of_the_number(self) -> None:
        tokens = self.tokens("largest=(32768, '/Constant_99')")
        self.assertEqual([t.raw for t in tokens], ["32768"])

    def test_percent_and_multiplier_forms(self) -> None:
        tokens = self.tokens("grows 22.6x and is 2.9% of the list")
        self.assertEqual(
            [(t.raw, t.form) for t in tokens],
            [("22.6x", "multiplier"), ("2.9%", "percent")],
        )

    def test_dotted_versions_are_one_token(self) -> None:
        tokens = self.tokens("python 3.11.15 and torch 2.7.1")
        self.assertEqual([t.raw for t in tokens], ["3.11.15", "2.7.1"])
        self.assertTrue(all(t.form == "dotted" for t in tokens))

    def test_digits_glued_to_an_identifier_are_not_numbers(self) -> None:
        # S128, float16, sha256 and T20 are identifiers, not claims.
        tokens = self.tokens("S128 float16 sha256 T20 int64 LEARN-10")
        self.assertEqual([t.raw for t in tokens], ["10"])

    def test_digest_needs_a_digit_and_a_letter_or_a_known_prefix(self) -> None:
        known = ["deadbeefdeadbeefdeadbeefdeadbeefdeadbeef" + "0" * 24]
        self.assertEqual(
            [t.raw for t in self.tokens("the word defaced is not a digest")],
            [],
        )
        tokens = self.tokens("digest a61ed2ef and deadbeefdead", known)
        self.assertEqual(
            sorted(t.raw for t in tokens), ["a61ed2ef", "deadbeefdead"])

    def test_truncated_digest_is_a_hex_token(self) -> None:
        tokens = self.tokens("quotes `a61ed2ef1e3f`")
        self.assertEqual([(t.raw, t.form) for t in tokens],
                         [("a61ed2ef1e3f", "hex")])

    def test_section_and_line_references_get_their_own_form(self) -> None:
        tokens = self.tokens("see section 5.4 and graph-inspection.md:725")
        self.assertEqual([(t.raw, t.form) for t in tokens],
                         [("5.4", "section-ref"), ("725", "line-ref")])

    def test_every_token_carries_file_and_line(self) -> None:
        tokens = self.tokens("first 12\nsecond 34\n")
        self.assertEqual([(t.where, t.raw) for t in tokens],
                         [("d.md:1", "12"), ("d.md:2", "34")])


# --------------------------------------------------------------------------
# Classification
# --------------------------------------------------------------------------


class ClassificationTests(unittest.TestCase):
    def test_bucket_invariant_holds_over_a_whole_document(self) -> None:
        text = (
            "The prefill graph has 8,753 nodes and 460 `Cast` nodes.\n"
            "It grows 1.32x. Section 5.4 covers 32,768 bytes of mask.\n"
            "Digest a61ed2ef. Model revision 28 layers. 99999999 unexplained.\n"
        )
        fixture = AuditFixture(text)
        buckets = fixture.buckets()
        self.assertEqual(
            sum(len(v) for v in buckets.values()), len(fixture.tokens))
        placed = [t for entries in buckets.values() for t, _ in entries]
        self.assertEqual(len(placed), len(set(id(t) for t in placed)))

    def test_a_literal_that_only_matches_the_baseline_moves(self) -> None:
        fixture = AuditFixture("prefill carries 8,753 nodes")
        self.assertEqual(fixture.bucket_of("8,753"), "MOVES")
        meaning = fixture.meanings_of("8,753")[0]
        self.assertEqual(meaning.baseline, 8753)
        self.assertEqual(meaning.current, 7634)
        self.assertTrue(meaning.needs_edit)

    def test_an_unchanged_value_is_static(self) -> None:
        # 341 prefill `Concat` nodes are unchanged by the re-export, and no
        # other measured value equals 341.
        fixture = AuditFixture("there are 341 `Concat` nodes")
        self.assertEqual(fixture.bucket_of("341"), "STATIC")

    def test_readings_that_share_a_fate_are_reported_but_not_ambiguous(
        self,
    ) -> None:
        # 254 is both the `MatMul` count and the external-initializer count,
        # in the fixtures and in the real graphs. Neither moves, so a reviewer
        # has one decision, not two -- but both readings are still carried.
        fixture = AuditFixture("there are 254 `MatMul` nodes")
        self.assertEqual(fixture.bucket_of("254"), "STATIC")
        keys = {m.key for m in fixture.meanings_of("254")}
        self.assertIn("count:op:*:*:MatMul", keys)
        self.assertIn("count:external_initializers:*:*", keys)

    def test_a_node_count_and_its_rule_population_move_together(self) -> None:
        # 8,753 is the node count and the node-count rule's own population.
        # Both move to 7,634, so this is MOVES rather than a false ambiguity.
        fixture = AuditFixture("prefill has 8,753 nodes")
        self.assertEqual(fixture.bucket_of("8,753"), "MOVES")
        self.assertGreater(len(fixture.meanings_of("8,753")), 1)

    def test_a_value_with_two_meanings_is_ambiguous(self) -> None:
        # 118 is prefill's ConstantOfShape count and decode's wide-IO count.
        fixture = AuditFixture("the count is 118")
        # The first moves to 62; the second does not move at all, so the
        # readings imply different actions.
        self.assertEqual(fixture.bucket_of("118"), "AMBIGUOUS")
        meanings = fixture.meanings_of("118")
        keys = {m.key for m in meanings}
        self.assertIn("count:op:*:*:ConstantOfShape", keys)
        self.assertIn("count:finding:*:*:R-WIDE-IO-BOUNDARY", keys)
        self.assertTrue(any(m.needs_edit for m in meanings))
        self.assertTrue(any(not m.needs_edit for m in meanings))

    def test_ambiguity_flags_whether_any_reading_moved(self) -> None:
        # 56 is the pre-promotion prefill `Pad` count and decode's
        # `ScatterElements` count; only the first moves.
        fixture = AuditFixture("56 appears twice")
        self.assertEqual(fixture.bucket_of("56"), "AMBIGUOUS")
        meanings = fixture.meanings_of("56")
        self.assertTrue(any(m.needs_edit for m in meanings))
        self.assertTrue(any(not m.needs_edit for m in meanings))

    def test_unexplained_numbers_are_unclassified(self) -> None:
        fixture = AuditFixture("an inline attribute of 26,706 bytes")
        self.assertEqual(fixture.bucket_of("26,706"), "UNCLASSIFIED")
        self.assertEqual(fixture.meanings_of("26,706"), [])

    def test_the_same_claim_at_four_contexts_is_one_meaning(self) -> None:
        # 460 `Cast` is measured at every variant. Without the collapse this
        # reads as several competing meanings and drowns the queue.
        fixture = AuditFixture("460 `Cast` nodes")
        self.assertEqual(fixture.bucket_of("460"), "STATIC")
        self.assertEqual(len(fixture.meanings_of("460")), 1)

    def test_a_superseded_digest_moves(self) -> None:
        fixture = AuditFixture("x")
        stale = fixture.pre_digest("S128", "prefill")
        fixture = AuditFixture(f"S128 prefill is `{stale}`")
        self.assertEqual(fixture.bucket_of(stale), "MOVES")

    def test_an_unchanged_decode_digest_is_static(self) -> None:
        fixture = AuditFixture("x")
        digest = fixture.post_digest("S128", "decode")
        fixture = AuditFixture(f"S128 decode is `{digest}`")
        self.assertEqual(fixture.bucket_of(digest), "STATIC")

    def test_a_denominator_that_only_appears_in_finding_prose_is_measured(
        self,
    ) -> None:
        fixture = AuditFixture("804 of 1,257 shape-defining inputs")
        self.assertEqual(fixture.bucket_of("1,257"), "MOVES")
        self.assertEqual(fixture.meanings_of("1,257")[0].current, 922)

    def test_a_ratio_is_matched_at_the_precision_written(self) -> None:
        # 2100000 / 1600000 = 1.3125 -> "1.31x"
        fixture = AuditFixture("the protobuf grows 1.31x from S128 to S512")
        self.assertIn(fixture.bucket_of("1.31x"), {"STATIC", "AMBIGUOUS"})
        keys = {m.key for m in fixture.meanings_of("1.31x")}
        self.assertTrue(any(k.startswith("ratio:onnx_bytes:") for k in keys))

    def test_a_percentage_is_matched_at_the_precision_written(self) -> None:
        # 254 MatMul of 7634 nodes = 3.3272...% -> "3.33%"
        fixture = AuditFixture("`MatMul` is 3.33% of the node list")
        keys = {m.key for m in fixture.meanings_of("3.33%")}
        self.assertIn("percent:op_share:*:*:MatMul", keys)

    def test_no_baseline_difference_means_no_moves(self) -> None:
        fixture = AuditFixture("prefill carries 8,753 nodes", post=False)
        self.assertEqual(fixture.buckets()["MOVES"], [])
        self.assertEqual(fixture.bucket_of("8,753"), "STATIC")


# --------------------------------------------------------------------------
# Citations
# --------------------------------------------------------------------------


class CitationTests(unittest.TestCase):
    def snapshot(self, **overrides):
        params = dict(POST)
        params.update(overrides)
        return audit.harvest(DictReader(evidence_files(**params)))

    def test_a_table_digest_that_disagrees_is_a_mismatch(self) -> None:
        snap = self.snapshot()
        stale = _digest("pad-S128-prefill")
        text = (
            "| Variant | Graph | Graph SHA-256 |\n"
            "|---|---|---|\n"
            f"| S128 | `S128/prefill.onnx` | `{stale}` |\n"
        )
        findings = audit.check_table_citations("d.md", text, snap)
        self.assertEqual(len(findings), 1)
        self.assertEqual(findings[0].severity, "mismatch")
        self.assertEqual(findings[0].where, "d.md:3")

    def test_a_table_digest_that_agrees_is_silent(self) -> None:
        snap = self.snapshot()
        good = _digest("concat-S128-prefill")
        text = (
            "| Variant | Graph | Graph SHA-256 |\n"
            "|---|---|---|\n"
            f"| S128 | `S128/prefill.onnx` | `{good}` |\n"
        )
        self.assertEqual(audit.check_table_citations("d.md", text, snap), [])

    def test_a_table_node_count_that_disagrees_is_a_mismatch(self) -> None:
        snap = self.snapshot()
        text = (
            "| Variant | Graph | Nodes | `.onnx` bytes |\n"
            "|---|---:|---:|---:|\n"
            "| S128 | prefill | 8,753 | 1,600,000 |\n"
        )
        findings = audit.check_table_citations("d.md", text, snap)
        self.assertEqual([f.severity for f in findings], ["mismatch"])
        self.assertIn("8,753", findings[0].detail)

    def test_a_table_row_that_agrees_is_silent(self) -> None:
        snap = self.snapshot()
        text = (
            "| Variant | Graph | Nodes | `.onnx` bytes |\n"
            "|---|---:|---:|---:|\n"
            "| S128 | prefill | 7,634 | 1,600,000 |\n"
        )
        self.assertEqual(audit.check_table_citations("d.md", text, snap), [])

    def test_an_annotated_cell_passes_when_one_number_is_measured(self) -> None:
        snap = self.snapshot()
        text = (
            "| Rule | Prefill count | Decode count |\n"
            "|---|---:|---:|\n"
            "| `R-WIDE-IO-BOUNDARY` | 58 | 118 |\n"
        )
        self.assertEqual(audit.check_table_citations("d.md", text, snap), [])

    def test_an_operator_span_that_disagrees_is_a_mismatch(self) -> None:
        snap = self.snapshot()
        findings = audit.check_operator_citations(
            "d.md", "the histogram shows `Cast=999`", snap)
        self.assertEqual([f.severity for f in findings], ["mismatch"])

    def test_an_operator_span_binds_the_kind_only_when_it_qualifies(
        self,
    ) -> None:
        snap = self.snapshot()
        # 459 is decode's Shape count. The trailing "prefill's 121" must not
        # bind this span to prefill.
        clean = ("it carries 459 `Shape` nodes against prefill's 121")
        self.assertEqual(audit.check_operator_citations("d.md", clean, snap), [])
        # An immediate qualifier does bind, and then the wrong kind fails.
        findings = audit.check_operator_citations(
            "d.md", "in prefill `Shape=459`", snap)
        self.assertEqual([f.severity for f in findings], ["mismatch"])

    def test_disagreeing_generated_sources_are_reported(self) -> None:
        files = evidence_files(**POST)
        manifest = json.loads(files["results/manifests/onnx/S128.json"])
        manifest["artifacts"]["prefill"]["sha256"] = _digest("something-else")
        files["results/manifests/onnx/S128.json"] = json.dumps(manifest)
        snap = audit.harvest(DictReader(files))
        findings = audit.check_evidence_conflicts(snap)
        identities = {f.where for f in findings}
        self.assertIn("digest:graph:S128:prefill", identities)
        self.assertTrue(all(f.severity == "conflict" for f in findings))

    def test_a_coherent_evidence_set_has_no_conflicts(self) -> None:
        self.assertEqual(audit.check_evidence_conflicts(self.snapshot()), [])

    def test_an_unresolved_digest_is_reported(self) -> None:
        snap = self.snapshot()
        classifier = audit.Classifier(snap, snap)
        known = classifier.known_digests()
        text = "the digest is `0123456789abcdef0123456789abcdef`"
        tokens = audit.tokenize("d.md", "reconcile", text, known)
        findings = audit.check_unresolved_digests("d.md", tokens, known)
        self.assertEqual([f.severity for f in findings], ["unresolved"])

    def test_a_known_digest_is_not_reported_as_unresolved(self) -> None:
        snap = self.snapshot()
        classifier = audit.Classifier(snap, snap)
        known = classifier.known_digests()
        text = f"the digest is `{_digest('concat-S128-prefill')}`"
        tokens = audit.tokenize("d.md", "reconcile", text, known)
        self.assertEqual(
            audit.check_unresolved_digests("d.md", tokens, known), [])

    def test_an_inline_digest_beside_its_graph_is_checked(self) -> None:
        snap = self.snapshot()
        stale = _digest("pad-S128-prefill")
        line = f"`S128/prefill.onnx` still reads `{stale}` today"
        findings = audit.check_inline_digest_citations("d.md", line, snap)
        self.assertEqual([f.severity for f in findings], ["mismatch"])


class ArtifactRehashTests(unittest.TestCase):
    def test_a_missing_artifact_root_degrades_cleanly(self) -> None:
        snap = audit.harvest(
            DictReader(evidence_files(**POST)),
            artifact_root=Path("/nonexistent/artifact/root"),
        )
        self.assertTrue(
            any("not present" in note for note in snap.notes), snap.notes)
        self.assertEqual(audit.check_evidence_conflicts(snap), [])

    def test_bytes_on_disk_are_compared_against_the_records(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "S128").mkdir()
            (root / "S128" / "prefill.onnx").write_bytes(b"not the graph")
            (root / "S128" / "decode.onnx").write_bytes(b"nor this")
            snap = audit.harvest(
                DictReader(evidence_files(**POST)), artifact_root=root)
            conflicts = {f.where for f in audit.check_evidence_conflicts(snap)}
            self.assertIn("digest:graph:S128:prefill", conflicts)
            self.assertIn("bytes:onnx:S128:prefill", conflicts)
            # S512 has no bytes on disk, so nothing is asserted about it.
            self.assertNotIn("digest:graph:S512:prefill", conflicts)

    def test_matching_bytes_produce_no_conflict(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            files = evidence_files(**POST)
            payload = b"the real graph bytes"
            digest = hashlib.sha256(payload).hexdigest()
            manifest = json.loads(files["results/manifests/onnx/S128.json"])
            manifest["artifacts"]["prefill"]["sha256"] = digest
            manifest["artifacts"]["prefill"]["size_bytes"] = len(payload)
            files["results/manifests/onnx/S128.json"] = json.dumps(manifest)
            config = json.loads(
                files["configs/models/qwen3-0.6b-onnx-export.json"])
            config["evidence_attestation"]["graph_sha256"]["S128"]["prefill"] = \
                digest
            files["configs/models/qwen3-0.6b-onnx-export.json"] = json.dumps(
                config)
            report = json.loads(files["results/graph/S128.json"])
            report["graphs"]["prefill"]["source_sha256"] = digest
            files["results/graph/S128.json"] = json.dumps(report)
            parity = json.loads(files["results/graph/parity/S128-ort-cpu.json"])
            parity["graph_digests"]["prefill"]["sha256"] = digest
            files["results/graph/parity/S128-ort-cpu.json"] = json.dumps(parity)
            (root / "S128").mkdir()
            (root / "S128" / "prefill.onnx").write_bytes(payload)
            snap = audit.harvest(DictReader(files), artifact_root=root)
            conflicts = {f.where for f in audit.check_evidence_conflicts(snap)}
            self.assertNotIn("digest:graph:S128:prefill", conflicts)
            self.assertNotIn("bytes:onnx:S128:prefill", conflicts)


class ArtifactRootResolutionTests(unittest.TestCase):
    """Which artifact tree the CLI agrees to re-hash.

    ``SLM_LAB_ARTIFACT_ROOT`` is ambient machine configuration. Honouring it
    while auditing some *other* repository root hashes one tree's graphs
    against another tree's records, which reports every digest as a conflict.
    """

    def resolve(self, repo_root: Path, override=None, env=None):
        environ = {} if env is None else {"SLM_LAB_ARTIFACT_ROOT": env}
        with mock.patch.dict(os.environ, environ, clear=True):
            return audit._resolve_artifact_root(repo_root, override)

    def test_no_ambient_variable_and_no_override_means_no_rehash(self) -> None:
        self.assertEqual(self.resolve(REPO_ROOT), (None, None))

    def test_the_ambient_variable_is_used_for_this_checkout(self) -> None:
        root, declined = self.resolve(REPO_ROOT, env="/store")
        self.assertEqual(root, Path("/store/onnx/reference/T20"))
        self.assertIsNone(declined)

    def test_the_ambient_variable_is_declined_for_another_root(self) -> None:
        root, declined = self.resolve(Path("/somewhere/else"), env="/store")
        self.assertIsNone(root)
        self.assertIn("SLM_LAB_ARTIFACT_ROOT", declined or "")
        self.assertIn("/somewhere/else", declined or "")

    def test_an_explicit_override_wins_over_the_ambient_variable(self) -> None:
        root, declined = self.resolve(
            Path("/somewhere/else"), override="/explicit", env="/store")
        self.assertEqual(root, Path("/explicit"))
        self.assertIsNone(declined)


class StaleSweepTests(unittest.TestCase):
    def test_a_superseded_digest_anywhere_in_the_tree_is_found(self) -> None:
        stale = _digest("pad-S128-prefill")
        current = audit.harvest(DictReader(evidence_files(**POST)))
        baseline = audit.harvest(DictReader(evidence_files(**PRE)))
        reader = DictReader({
            "docs/somewhere/else.md": f"an old note quoting {stale}\n",
            "docs/clean.md": "no digests here\n",
        })
        findings = audit.sweep_stale_digests(reader, current, baseline)
        self.assertEqual([f.where for f in findings],
                         ["docs/somewhere/else.md:1"])
        self.assertEqual(findings[0].severity, "stale")

    def test_nothing_is_stale_when_the_snapshots_agree(self) -> None:
        snap = audit.harvest(DictReader(evidence_files(**POST)))
        reader = DictReader({"docs/x.md": "text\n"})
        self.assertEqual(audit.sweep_stale_digests(reader, snap, snap), [])


class EndToEndCliTests(unittest.TestCase):
    """Drive the CLI over a throwaway git repository."""

    def _repo(self, tmp: Path, doc_text: str) -> Path:
        root = tmp / "repo"
        root.mkdir()
        env_git = ["git", "-C", str(root)]
        subprocess.run(env_git + ["init", "-q"], check=True)
        subprocess.run(env_git + ["config", "user.email", "t@example.com"],
                       check=True)
        subprocess.run(env_git + ["config", "user.name", "T"], check=True)
        for relpath, text in evidence_files(**PRE).items():
            path = root / relpath
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
        (root / "docs" / "results" / "onnx").mkdir(parents=True, exist_ok=True)
        (root / "docs" / "results" / "onnx" / "graph-inspection.md").write_text(
            doc_text, encoding="utf-8")
        subprocess.run(env_git + ["add", "-A"], check=True)
        subprocess.run(env_git + ["commit", "-qm", "pre"], check=True)
        return root

    def _run(self, argv: Sequence[str]) -> tuple:
        buffer = io.StringIO()
        with redirect_stdout(buffer):
            code = audit.main(list(argv))
        return code, buffer.getvalue()

    def setUp(self) -> None:
        self._saved_documents = audit.CLAIM_DOCUMENTS
        audit.CLAIM_DOCUMENTS = (
            ("docs/results/onnx/graph-inspection.md", "reconcile"),
        )
        # These fixtures are complete repositories in their own right, so the
        # machine's artifact store must not reach into them. Each test that
        # cares about the ambient variable sets it itself.
        patcher = mock.patch.dict(os.environ, {}, clear=False)
        patcher.start()
        os.environ.pop("SLM_LAB_ARTIFACT_ROOT", None)
        self.addCleanup(patcher.stop)

    def tearDown(self) -> None:
        audit.CLAIM_DOCUMENTS = self._saved_documents

    def test_citations_exits_zero_on_a_consistent_tree(self) -> None:
        text = (
            "| Variant | Graph | Nodes |\n"
            "|---|---|---:|\n"
            "| S128 | prefill | 8,753 |\n"
        )
        with TemporaryDirectory() as tmp:
            root = self._repo(Path(tmp), text)
            code, out = self._run(["citations", "--repo-root", str(root)])
        self.assertEqual(code, 0, out)
        self.assertIn("no disagreements", out)

    def test_an_ambient_artifact_root_does_not_reach_into_another_tree(
        self,
    ) -> None:
        # Regression: the tool used to read SLM_LAB_ARTIFACT_ROOT whatever it
        # had been pointed at, so a machine with the variable exported re-hashed
        # the real graphs and reported six conflicts against these fixtures.
        text = (
            "| Variant | Graph | Nodes |\n"
            "|---|---|---:|\n"
            "| S128 | prefill | 8,753 |\n"
        )
        with TemporaryDirectory() as tmp:
            root = self._repo(Path(tmp), text)
            store = Path(tmp) / "store"
            (store / "onnx" / "reference" / "T20" / "S128").mkdir(parents=True)
            (store / "onnx" / "reference" / "T20" / "S128"
             / "prefill.onnx").write_bytes(b"a different repository's graph")
            with mock.patch.dict(
                os.environ, {"SLM_LAB_ARTIFACT_ROOT": str(store)}
            ):
                code, out = self._run(["citations", "--repo-root", str(root)])
        self.assertEqual(code, 0, out)
        self.assertIn("no disagreements", out)
        self.assertIn("declined the ambient SLM_LAB_ARTIFACT_ROOT", out)

    def test_an_explicit_artifact_root_is_still_honoured(self) -> None:
        # The decline is about ambient configuration, not about re-hashing:
        # naming the path asserts that those bytes belong to these records.
        text = "nothing to bind here\n"
        with TemporaryDirectory() as tmp:
            root = self._repo(Path(tmp), text)
            store = Path(tmp) / "explicit"
            (store / "S128").mkdir(parents=True)
            (store / "S128" / "prefill.onnx").write_bytes(b"wrong bytes")
            code, out = self._run([
                "citations", "--repo-root", str(root),
                "--artifact-root", str(store),
            ])
        self.assertEqual(code, 1, out)
        self.assertIn("digest:graph:S128:prefill", out)

    def test_citations_exits_non_zero_after_the_evidence_moves(self) -> None:
        text = (
            "| Variant | Graph | Nodes |\n"
            "|---|---|---:|\n"
            "| S128 | prefill | 8,753 |\n"
        )
        with TemporaryDirectory() as tmp:
            root = self._repo(Path(tmp), text)
            for relpath, body in evidence_files(**POST).items():
                (root / relpath).write_text(body, encoding="utf-8")
            code, out = self._run(["citations", "--repo-root", str(root)])
        self.assertEqual(code, 1)
        self.assertIn("8,753", out)
        self.assertIn("What this does not prove", out)

    def test_claims_reports_moves_against_the_pre_promotion_commit(self) -> None:
        text = "The prefill graph carries 8,753 nodes.\n"
        with TemporaryDirectory() as tmp:
            root = self._repo(Path(tmp), text)
            for relpath, body in evidence_files(**POST).items():
                (root / relpath).write_text(body, encoding="utf-8")
            code, out = self._run(
                ["claims", "--repo-root", str(root), "--json"])
        self.assertEqual(code, 0)
        payload = json.loads(out)
        moves = payload["buckets"]["MOVES"]
        self.assertEqual([m["literal"] for m in moves], ["8,753"])
        self.assertEqual(moves[0]["meanings"][0]["current"], 7634)
        self.assertEqual(
            payload["total_tokens"],
            sum(len(v) for v in payload["buckets"].values()),
        )

    def test_claims_says_so_when_the_baseline_cannot_show_movement(self) -> None:
        text = "The prefill graph carries 8,753 nodes.\n"
        with TemporaryDirectory() as tmp:
            root = self._repo(Path(tmp), text)
            code, out = self._run(["claims", "--repo-root", str(root)])
        self.assertEqual(code, 0)
        self.assertIn("empty by construction", out)
        self.assertIn("UNCLASSIFIED", out)


if __name__ == "__main__":
    unittest.main()
